Models/TopUp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace webapp.Models
{
    public class TopUp
    {
        public int Id { get; set; }

        public int TopUpCardId { get; set; }

        [ForeignKey("TopUpCardId")]
        public TopUpCard TopUpCard { get; set; }

        public string AppUserId { get; set; }

        [ForeignKey("AppUserId")]
        public AppUser AppUser { get; set; }

        public DateTime TopUpDate { get; set; }
    }
}

Models/Wallet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace webapp.Models
{
    public class Wallet

    {
        public int Id { get; set; }

        public string AppUserId { get; set; }

        [ForeignKey("AppUserId")]
        public AppUser AppUser { get; set; }

        public float Credits { get; set; }

        public int Discount { get; set; }
    }
}

Areas/Organizer/Controllers/WalletController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using webapp.Areas.Organizer.Helpers;
using webapp.Context;
using webapp.Models;
using webapp.ViewModels;

namespace webapp.Areas.Organizer.Controllers
{
    [Area("Organizer")]
    [Authorize]
    [ServiceFilter(typeof(CustomExceptionFilter))]
    public class WalletController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WalletController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {

            var userID = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

            if (_context.Wallet.Where(k => k.AppUserId == userID).FirstOrDefault()==null)
            {
                _context.Add(new Wallet { AppUserId = userID, Credits = 0, Discount = 0 });

                _context.SaveChanges();
            }

            ViewData["_LayoutNavbarBG"] = "background-color: black;";
            ViewData["_layoutBackgroundImg-key"] = "/images/WalletBackground.jpg";
            ViewData["_layoutBackgroundStyle-key"] = "background-size: 100% 100%; background-attachment: fixed";
            ViewData["EOCreditsAmount-key"] = _context.Wallet.Where(k => k.AppUserId == userID).FirstOrDefault().Credits;

            return View();
        }

        public IActionResult Funds()
        {
            var userID = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            ViewData["EOCreditsAmountF-key"] = (float)_context.Wallet.Where(k => k.AppUserId == userID).FirstOrDefault().Credits;
            return PartialView();
        }

        /*public IActionResult TopUp(string Code)
        {

            TempData["TopUpCounter-key"] = 0;

            if (Code == null)
                return PartialView();
            else
            {
                var userID = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

                TopUpCard TUC = _context.TopUpCard.Where(x => x.Code == Code).FirstOrDefault();

                TopUp TU = new TopUp
                {
                    TopUpCardId = TUC.Id,
                    AppUserId = userID,
                    TopUpDate = DateTime.Now
                };

                Wallet WLT = _context.Wallet.Where(k => k.AppUserId == userID).FirstOrDefault();

                WLT.Credits += (float)TUC.Amount;

                _context.Update(WLT);

                _context.Add(TU);

                _context.SaveChanges();

                //ViewData["Message-key"] = "Successfully added!";
                //return Content("Successfully added!");

                return PartialView();
            }

            //return PartialView();
        }*/

        [HttpGet]
        public IActionResult TopUp()
        {
            WalletVm vm = new WalletVm();
            return PartialView(vm);
        }

        [HttpPost]
        public IActionResult TopUp(WalletVm vm)
        {

                var userID = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

                TopUpCard TUC = _context.TopUpCard.Where(x => x.Code == vm.CardCode).FirstOrDefault();

            if(TUC==null)
            {
                return Content("Top up card not found!");
            }

            if (_context.TopUp.Include(x=>x.TopUpCard).Any(x => x.TopUpCard.Code == vm.CardCode))
            {
                return Content("Top up card already used!");
            }

            TopUp TU = new TopUp
                {
                    TopUpCardId = TUC.Id,
                    AppUserId = userID,
                    TopUpDate = DateTime.Now
                };

                Wallet WLT = _context.Wallet.Where(k => k.AppUserId == userID).FirstOrDefault();

                WLT.Credits += (float)TUC.Amount;

                _context.Update(WLT);

                _context.Add(TU);

                _context.SaveChanges();

            //ViewData["Message-key"] = "Successfully added!";
            //return Content("Successfully added!");

            return PartialView();

        }  
        
        public IActionResult TopUpIndex ()
        {
            var userID = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();

            List<TopUp> topUps = _context.TopUp.Include(x => x.TopUpCard).Where(x => x.AppUserId == userID).ToList();

            ViewData["topUps-key"] = topUps;

            return PartialView();
        }

    }
}

Areas/Organizer/Views/Wallet/Funds.cshtml
@{
    float EOCreditsAmountF = (float)ViewData["EOCreditsAmountF-key"];
}

<br />
<center><i class="glyphicon glyphicon-bitcoin" style="font-size: 3em;"></i><br /><br /><p style="display: inline;" class="creditsAmount">You have @EOCreditsAmountF credits available.</p></center>
<br/>
<br />

Areas/Organizer/Views/Wallet/Index.cshtml
@{
    float EOCreditsAmount = (float)ViewData["EOCreditsAmount-key"];
}



<div class="col-md-4 col-md-offset-4 formaGridMarginTop well" style="height: 40%; border-radius: 10px; text-align: center; background-color: rgba(255, 255, 255, 0.75);">


    <div class="btn-group" style="top: 0; position: relative;">
        <a class="TopUpButtonPrompt btn btn-primary" href="/Organizer/Wallet/Funds" ajax-poziv="da" ajax-rezultat="ajaxDiv">Wallet info</a>
        <a class="TopUpButtonPrompt btn btn-primary" href="/Organizer/Wallet/TopUp" ajax-poziv="da" ajax-rezultat="ajaxDiv">Top Up Wallet</a>
        <a class="TopUpButtonPrompt btn btn-info" href="/Organizer/Wallet/TopUpIndex" ajax-poziv="da" ajax-rezultat="ajaxDiv">Top Up history</a>
    </div>
    <br />
    <br />
    <br />

    <div id="ajaxDiv">
        <br />
        <center><i class="glyphicon glyphicon-bitcoin" style="font-size: 3em;"></i><br /><br /><p style="display: inline;" class="creditsAmount">You have @EOCreditsAmount credits available.</p></center>
        <br />
        <br />
    </div>

</div>

Areas/Organizer/Views/Wallet/TopUp.cshtml
@model WalletVm
<br />
<center><p style="font-size: 1.5em">Card number</p></center>
<form id="form1" asp-action="TopUp" asp-controller="Wallet" ajax-poziv="da" ajax-rezultat="ajaxDiv">
    <input type="text" asp-for="CardCode" class="form-control" />
    <br />
    <br />
    <input class="btn btn-primary" type="submit" value="Top Up!" />
</form>
<br />

Areas/Organizer/Views/Wallet/TopUpIndex.cshtml
@{
    var topUps = (List<TopUp>)ViewData["topUps-key"];
}

<table class="table">
    <thead>
        <tr>
            <th><center>Date</center></th>
            <th><center>Amount</center></th>
            <th><center>Card number</center></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var x in topUps)
        {
        <tr class="rowTopUp">
            <td>@(x.TopUpDate.Day + "." + x.TopUpDate.Month + "." + x.TopUpDate.Year)</td>
            <td>@x.TopUpCard.Amount</td>
            <td>@x.TopUpCard.Code</td>
        </tr>
        }
    </tbody>
</table>